#!/usr/bin/env ruby
require_relative "lib/screen.rb"
require_relative "lib/speaker.rb"
require_relative "lib/bubble.rb"
require_relative "lib/wrapper.rb"
require_relative "lib/saymore.rb"

if true
require 'pry'
require 'pry-nav'
require 'awesome_print'
end

opts = {
  speaker: 'whale',
  bubble: 'dashes',
  width: 40
}

opt = ARGV.shift
while opt
  if opt == '-s' || opt == '--speaker'
    opts[:speaker] = ARGV.shift
  elsif opt == '-b' || opt == '--bubble'
    opts[:bubble] = ARGV.shift
  elsif opt == '-w' || opt == '--width' || opt == '--max-width'
    opts[:width] = ARGV.shift.to_i rescue 40
  else
    puts "Unknown arg: #{opt}"
    exit 1
  end
  opt = ARGV.shift
end

text = ARGF.read
puts Saymore.go!(opts[:speaker], opts[:bubble], text, width: opts[:width])
